version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: eurobet-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d